### ISSUE TITLE
bugs with sort import

### ISSUE THREAD

**Issue by B2o5T** [the-guild-org/shared-config#244]
1. css should be last

<img width="1265" alt="image" src="https://github.com/the-guild-org/shared-config/assets/7361780/3ad2e0b8-fc5c-49c2-8f5b-ad5273ff8ba5">

2. still sort side-effects imports

<img width="1282" alt="image" src="https://github.com/the-guild-org/shared-config/assets/7361780/4022e1d0-ade3-49b6-b144-883bfa34b256">

3. broken comments

<img width="1241" alt="image" src="https://github.com/the-guild-org/shared-config/assets/7361780/feec4695-8097-4a28-b1df-971f4db299b6">

**Comment by enisdenjo** [comment]
> 1. css should be last

I'll check it out - what repository is this?

> 2. still sort side-effects imports

[@ianvs/prettier-plugin-sort-imports](https://github.com/IanVS/prettier-plugin-sort-imports) should not sort side-effect imports at all - it should keep them as is. Is the issue here that it doesn't sort (working as expected) or that it does sort (not working as expected)?

> 3. broken comments

Is this very important?

**Comment by B2o5T** [comment]
> I'll check it out - what repository is this?

https://github.com/the-guild-org/website/blob/a03627703e0d8cbebf2b8d38b3900c12d1aff044/website/pages/_app.mdx?plain=1#L3

> [@ianvs/prettier-plugin-sort-imports](https://github.com/IanVS/prettier-plugin-sort-imports) should not sort side-effect imports at all - it should keep them as is. Is the issue here that it doesn't sort (working as expected) or that it does sort (not working as expected)?

as you can see in code block it was sorted

> Is this very important?

I think it's a bug and should be reported

**Comment by enisdenjo** [comment]
@B2o5T we've never released the new prettier config haha. Is in the pipes now: https://github.com/the-guild-org/shared-config/pull/214.

Using the new plugin:

1. That import is considered a side-effect, so it will not be sorted - it'll stay exactly where placed.
2. Same ^
3. Seems to be an upstream issue with babel ([see test in plugin repo](https://github.com/IanVS/prettier-plugin-sort-imports/blob/cd836a3030073253032ba4a8e9668146cd1c902e/tests/ImportCommentsPreserved/import-comments-babel-pulling-single-line-bug.ts))
